### Chat
POST {{baseUrl}} HTTP/1.1
Content-Type: application/json

{
    "inputMessage": "Hello!",
    "historySummary": ""
}

### Get Urls
Post {{baseUrl}}/urls HTTP/1.1
Content-Type: application/json 

{
    "url": ""
}

### Scan website
Post {{baseUrl}}/scan HTTP/1.1
Content-Type: application/json

{
    "url": ""
}